### ISSUE TITLE
`TEST ISSUE` in some missing ancestor reorg tests

### ISSUE THREAD

**Issue by Rjected** [ethereum/hive#1135]
When running:
```
Invalid Missing Ancestor Syncing ReOrg, GasLimit, EmptyTxs=False, CanonicalReOrg=True, Invalid P8
```

I get:
```
FAIL (Invalid Missing Ancestor Syncing ReOrg, GasLimit, EmptyTxs=False, CanonicalReOrg=True, Invalid P8): TEST ISSUE - Failed to set invalid block: triedb layer [0x5bb856b70f63d46b95dff7d2b07700194311a87c8a7494ad0de0e72de23d624b] is disk layer
```

We caught these when testing recent updates to our CI which should improve catching individual test regressions. I'm not really sure how to fix this, but it says `TEST ISSUE` and fails on reth / geth / erigon, so I assume this is a hive issue.

**Comment by maintenance00** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
Thank you for posting @Rjected

**Comment by Rjected** [comment]
just bumping this issue as we are currently rewriting a lot of engine logic, and having coverage from these tests would be great

**Comment by marioevz** [comment]
Sorry about the delay, taking a look today!

**Comment by marioevz** [comment]
The problem seems to be in the geth node module we use to simulate a client delivering bad blocks through the p2p network: https://github.com/ethereum/hive/blob/master/simulators/ethereum/engine/client/node/node.go

Since the error suggests that tree leaf could not be modified since it made its way to the disk, I tried modifying the parameters for the database cache to no success: https://github.com/ethereum/hive/blob/8fd042df2589702118bea85e793ed1e5d461dec5/simulators/ethereum/engine/client/node/node.go#L208-L209

Will keep looking into it.
