### ISSUE TITLE
Figure out some way of running simulations (p2p) without needing Hive locally.

### ISSUE THREAD

**Issue by FrankSzendzielarz** [ethereum/hive#226]
Requested by @fjl . Possible solutions range across ideas like remote version of Hive to permitting simulations to run standalone somehow against local docker images.

**Comment by fjl** [comment]
That's not really what I requested :). What I'd like to do is to run the devp2p suite outside of hive against any endpoint. To make this happen, we'd need to change the tests to make interaction with the hive simulation API optional. 

The devp2p test needs the API for two things: to spawn the node under test and to spawn the relay container. Since the client is already up in my use case we don't need to spawn it. The relayer address can just be a CLI flag.

**Comment by FrankSzendzielarz** [comment]
Gotcha. <thumbs up emoji here>

**Comment by fjl** [comment]
We have now implemented the stand-alone peer-to-peer tests in the go-ethereum devp2p command line tool. The eth protocol tests are now in Hive, so closing this. Running simulations stand-alone is not supported anymore.
