### ISSUE TITLE
Dramatically improve the front end results view

### ISSUE THREAD

**Issue by FrankSzendzielarz** [ethereum/hive#227]
Improve the UI
Make the json format more friendly and documented

**Comment by fjl** [comment]
My feedback on the version of the new UI (as of commit 423010c) that's deployed at https://hivetests.ethdevops.io.

- The page header content should be left-aligned instead of centered.
- Test results open in a popup. They should open in a new browser tab instead.
- It's weird to have two options ("inline" and "open") for opening the results. Just pick one.
  I vote for removing the inline option because it doesn't seem to have all the features of the dedicated view.
- Result filters ('passes', 'fails') should be check-boxes instead of buttons.
- We need a better logo and a link to the hive repo.

**Comment by fjl** [comment]
We are now using the result view from https://github.com/holiman/testreport_template and it works very well.
